namespace Microsoft.Fixture;

using System.Reflection;

codeunit 50241 "Metadata Roundtrip"
{
    procedure Exercise(): Integer
    var
        Metadata: Record "Page Metadata" temporary;
        Reflected: RecordRef;
        Ordinal: Integer;
        Identifier: Guid;
    begin
        Metadata.PageType := Metadata.PageType::Card;
        Ordinal := Metadata.PageType;
        if Ordinal <> 0 then Error('Card ordinal');
        Metadata.PageType := Metadata.PageType::List;
        Ordinal := Metadata.PageType;
        if Ordinal <> 1 then Error('List ordinal');
        Metadata.PageType := Metadata.PageType::RoleCenter;
        Ordinal := Metadata.PageType;
        if Ordinal <> 2 then Error('RoleCenter ordinal');
        Metadata.PageType := Metadata.PageType::CardPart;
        Ordinal := Metadata.PageType;
        if Ordinal <> 3 then Error('CardPart ordinal');
        Metadata.PageType := Metadata.PageType::ListPart;
        Ordinal := Metadata.PageType;
        if Ordinal <> 4 then Error('ListPart ordinal');
        Metadata.PageType := Metadata.PageType::Document;
        Ordinal := Metadata.PageType;
        if Ordinal <> 5 then Error('Document ordinal');
        Metadata.PageType := Metadata.PageType::Worksheet;
        Ordinal := Metadata.PageType;
        if Ordinal <> 6 then Error('Worksheet ordinal');
        Metadata.PageType := Metadata.PageType::ListPlus;
        Ordinal := Metadata.PageType;
        if Ordinal <> 7 then Error('ListPlus ordinal');
        Metadata.PageType := Metadata.PageType::ConfirmationDialog;
        Ordinal := Metadata.PageType;
        if Ordinal <> 8 then Error('ConfirmationDialog ordinal');
        Metadata.PageType := Metadata.PageType::NavigatePage;
        Ordinal := Metadata.PageType;
        if Ordinal <> 9 then Error('NavigatePage ordinal');
        Metadata.PageType := Metadata.PageType::StandardDialog;
        Ordinal := Metadata.PageType;
        if Ordinal <> 10 then Error('StandardDialog ordinal');
        Metadata.PageType := Metadata.PageType::API;
        Ordinal := Metadata.PageType;
        if Ordinal <> 11 then Error('API ordinal');
        Metadata.PageType := Metadata.PageType::HeadlinePart;
        Ordinal := Metadata.PageType;
        if Ordinal <> 12 then Error('HeadlinePart ordinal');
        Metadata.SetRange(PageType, Metadata.PageType::HeadlinePart);
        Ordinal := Metadata.GetRangeMin(PageType);
        if Ordinal <> 12 then Error('HeadlinePart typed range');
        if Format(Metadata.PageType) <> 'HeadlinePart' then Error('HeadlinePart format');
        if Metadata.FieldNo(Editable) <> 4 then Error('Editable field identity');
        if Metadata.FieldNo(PageType) <> 5 then Error('PageType field identity');
        if Metadata.FieldNo("DataCaptionExpr.") <> 7 then Error('Caption expression field identity');
        if Metadata.FieldNo(SourceTable) <> 14 then Error('SourceTable field identity');
        if Metadata.FieldNo("App ID") <> 29 then Error('App identity field');
        if Metadata.FieldNo("AL Namespace") <> 32 then Error('Namespace field identity');
        Metadata.ID := 50242;
        Metadata.SourceTable := 18;
        Metadata.CardPageID := 21;
        if (Metadata.ID <> 50242) or (Metadata.SourceTable <> 18) or (Metadata.CardPageID <> 21) then Error('Integer fields');
        Metadata.Name := 'Original AL Name';
        Metadata.Caption := 'Visible Caption';
        if (Metadata.Name <> 'Original AL Name') or (Metadata.Caption <> 'Visible Caption') then Error('Name and caption');
        Metadata."DataCaptionExpr." := 'Caption expression';
        Metadata.APIPublisher := 'agiru';
        Metadata.APIGroup := 'erp';
        Metadata.APIVersion := 'v1.0';
        Metadata.EntityName := 'customer';
        Metadata.EntitySetName := 'customers';
        Metadata.SourceTableView := 'sorting(No.)';
        Metadata.DataCaptionFields := 'No.,Name';
        Metadata.InherentPermissions := 'rX';
        Metadata.InherentEntitlements := 'X';
        Metadata."AL Namespace" := 'Microsoft.Fixture';
        if (Metadata."DataCaptionExpr." <> 'Caption expression') or (Metadata.APIPublisher <> 'agiru') or (Metadata.APIGroup <> 'erp') or (Metadata.APIVersion <> 'v1.0') or (Metadata.EntityName <> 'customer') or (Metadata.EntitySetName <> 'customers') or (Metadata.SourceTableView <> 'sorting(No.)') or (Metadata.DataCaptionFields <> 'No.,Name') or (Metadata.InherentPermissions <> 'rX') or (Metadata.InherentEntitlements <> 'X') or (Metadata."AL Namespace" <> 'Microsoft.Fixture') then Error('Original Text fields');
        Metadata.Editable := true;
        Metadata.RefreshOnActivate := true;
        Metadata.InsertAllowed := true;
        Metadata.ModifyAllowed := true;
        Metadata.DeleteAllowed := true;
        Metadata.DelayedInsert := true;
        Metadata.ShowFilter := true;
        Metadata.MultipleNewLines := true;
        Metadata.SaveValues := true;
        Metadata.AutoSplitKey := true;
        Metadata.SourceTableTemporary := true;
        Metadata.LinksAllowed := true;
        Metadata.ChangeTrackingAllowed := true;
        Metadata.PopulateAllFields := true;
        if not Metadata.Editable or not Metadata.RefreshOnActivate or not Metadata.InsertAllowed or not Metadata.ModifyAllowed or not Metadata.DeleteAllowed or not Metadata.DelayedInsert or not Metadata.ShowFilter or not Metadata.MultipleNewLines or not Metadata.SaveValues or not Metadata.AutoSplitKey or not Metadata.SourceTableTemporary or not Metadata.LinksAllowed or not Metadata.ChangeTrackingAllowed or not Metadata.PopulateAllFields then Error('Original Boolean fields');
        Identifier := CreateGuid();
        Metadata."App ID" := Identifier;
        if Metadata."App ID" <> Identifier then Error('Original Guid field');
        Reflected.GetTable(Metadata);
        if Reflected.Field(5).OptionMembers() <> 'Card,List,RoleCenter,CardPart,ListPart,Document,Worksheet,ListPlus,ConfirmationDialog,NavigatePage,StandardDialog,API,HeadlinePart' then Error('Source option reflection');
        exit(27);
    end;
}
