#include "dotnet/Encoding.h"
#include "dotnet/HashAlgorithm.h"
#include "dotnet/Regex.h"
#include "runtime/ErrorValue.h"
#include "type/Integer.h"

#include "Check.h"
#include "Reference.h"
#include "fixture/codeunit/HashConsumer.h"

#include <array>
#include <string>
#include <string_view>
#include <utility>

namespace {

std::string Raw(const agiru::dotnet::Array &bytes) {
  std::string result;
  for (const auto &cell : bytes) {
    const agiru::Integer value = cell;
    result.push_back(static_cast<char>(value));
  }
  return result;
}

void Disposal(agiru::Fixture::HashConsumer_Codeunit &consumer) {
  auto hash = agiru::dotnet::HashAlgorithm::Create("SHA256");
  consumer.DisposeByValue(hash);
  bool rejected = false;
  try {
    (void)hash.ComputeHash(agiru::dotnet::Encoding::UTF8().GetBytes("abc"));
  } catch (const agiru::Error &) { rejected = true; }
  CHECK_TRUE("generated by-value Dispose affects the caller", rejected);
  CHECK_TRUE("generated unknown factory keeps null identity", consumer.UnknownIsNull());
}

}

int main() {
  return gate::Run("Generated Hash Algorithms", [] {
    agiru::Fixture::HashConsumer_Codeunit consumer;
    constexpr std::array<std::pair<std::string_view, std::string_view>, 5> vectors{{
        {"MD5", "900150983CD24FB0D6963F7D28E17F72"},
        {"SHA1", "A9993E364706816ABA3E25717850C26C9CD0D89D"},
        {"SHA256", "BA7816BF8F01CFEA414140DE5DAE2223B00361A396177A9CB410FF61F20015AD"},
        {"SHA384",
         "CB00753F45A35E8BB5A03D699AC65007272C32AB0EDED1631A8B605A43FF5BED8086072BA1E7"
         "CC2358BAECA134C825A7"},
        {"SHA512",
         "DDAF35A193617ABACC417349AE20413112E6FA4E89A97EA20A9EEEE64B55D39A2192992A274"
         "FC1A836BA3C23A3FEEBBD454D4423643CE80E2A9AC94FA54CA49F"},
    }};
    for (const auto &[name, expected] : vectors) {
      CHECK_TEXT("generated named hash returns original CLR bytes",
                 Raw(consumer.HashText("abc", name)),
                 gate::Unhex(expected));
      const auto bytes = agiru::dotnet::Encoding::UTF8().GetBytes("xabcx");
      CHECK_TEXT("generated overload hashes only its declared region",
                 Raw(consumer.HashRegion(bytes, name, 1, 3)),
                 gate::Unhex(expected));
    }
    CHECK_TEXT("generated Unicode path is UTF-8 without a BOM",
               Raw(consumer.HashText("ä😀", "SHA256")),
               gate::Unhex("41CDB6F90A10B81F7BB0B8654E469A8866B8D24988D1BB2706DADC3641A8DB3B"));
    Disposal(consumer);
  });
}
