#include "dotnet/Encoding.h"
#include "dotnet/Regex.h"
#include "runtime/ErrorValue.h"
#include "type/BigText.h"
#include "type/Integer.h"
#include "type/Variant.h"

#include "Check.h"
#include "fixture/codeunit/ByteConversionConsumer.h"
#include "fixture/codeunit/ImplicitByteArrayConsumer.h"

#include <string>
#include <string_view>

namespace {

std::string Raw(const agiru::dotnet::Array &bytes) {
  std::string result;
  for (const auto &cell : bytes) {
    const agiru::Integer value = cell;
    CHECK_TRUE("generated decoded cells are typed unsigned Integers",
               cell.IsInteger() && value >= 0 && value <= 255);
    result.push_back(static_cast<char>(value));
  }
  return result;
}

template <typename Operation> bool Fails(Operation operation) {
  try {
    operation();
  } catch (const agiru::Error &) { return true; }
  return false;
}

void Boundaries(agiru::Fixture::ByteConversionConsumer_Codeunit &consumer) {
  const auto utf8 = agiru::dotnet::Encoding::UTF8();
  const auto bytes = utf8.GetBytes("xabcx");
  CHECK_TEXT("generated exact region excludes surrounding cells",
             consumer.EncodeRegion(bytes, 1, 3, 0),
             "YWJj");
  CHECK_TEXT(
      "generated empty end-position region is valid", consumer.EncodeRegion(bytes, 5, 0, 0), "");
  CHECK_TRUE("generated range overflow refuses",
             Fails([&] { (void)consumer.EncodeRegion(bytes, 1, 5, 0); }));
  CHECK_TRUE("generated invalid formatting refuses on empty input",
             Fails([&] { (void)consumer.EncodeRegion(utf8.GetBytes(""), 0, 0, 2); }));
  for (const auto value : {-1, 256}) {
    agiru::dotnet::Array invalid;
    invalid.Add(agiru::Variant{agiru::Integer{value}});
    CHECK_TRUE("generated invalid byte cells refuse rather than wrap",
               Fails([&] { (void)consumer.Encode(invalid); }));
  }
  CHECK_TRUE("numeric conversions remain explicit gaps",
             Fails([&] { (void)consumer.UnsupportedNumber(); }));
}

}

int main() {
  return gate::Run("Generated Byte Conversion", [] {
    agiru::Fixture::ByteConversionConsumer_Codeunit consumer;
    agiru::Fixture::ImplicitByteArrayConsumer_Codeunit implicit;
    CHECK_TRUE("generated implicit return-value dependency compiles without PCH",
               implicit.DecodeLength("AP+A") == 3);
    CHECK_TRUE("generated BigText carrier retains its named unsupported adapter",
               Fails([&] { (void)consumer.DecodeBigText(agiru::BigText{}); }));
    const auto utf8 = agiru::dotnet::Encoding::UTF8();
    CHECK_TEXT(
        "generated encoding adds no UTF-8 BOM", consumer.Encode(utf8.GetBytes("abc")), "YWJj");
    CHECK_TEXT(
        "generated empty array encodes to empty text", consumer.Encode(utf8.GetBytes("")), "");
    CHECK_TEXT("generated decoder preserves original bytes",
               Raw(consumer.Decode("AP+A")),
               std::string_view("\0\xff\x80", 3));
    CHECK_TEXT("generated whitespace decoder keeps the CLR profile",
               Raw(consumer.Decode("T Q=\n=\r\t")),
               "M");
    CHECK_TRUE("generated incomplete input refuses", Fails([&] { (void)consumer.Decode("TQ="); }));
    CHECK_TRUE("generated transform-only padding acceptance is not substituted",
               Fails([&] { (void)consumer.Decode("TQ==TQ=="); }));
    const std::string line(57, 'a');
    const auto plain = consumer.Encode(utf8.GetBytes(line));
    CHECK_TEXT("generated typed formatting enum starts the next group on a new line",
               consumer.EncodeLines(utf8.GetBytes(line + "a")),
               plain + "\r\nYQ==");
    const std::string large(7297, 'a');
    constexpr unsigned kFullLinesInSample = 128;
    std::string formatted;
    for (unsigned index = 0; index < kFullLinesInSample; ++index) { formatted += plain + "\r\n"; }
    formatted += "YQ==";
    CHECK_TEXT("generated formatting retains CRLF across every block seam",
               consumer.EncodeLines(utf8.GetBytes(large)),
               formatted);
    CHECK_TEXT("generated multi-block plain conversion retains every byte",
               Raw(consumer.Decode(consumer.Encode(utf8.GetBytes(large)))),
               large);
    CHECK_TEXT("generated multi-block line formatting retains every byte",
               Raw(consumer.Decode(consumer.EncodeLines(utf8.GetBytes(large)))),
               large);
    Boundaries(consumer);
  });
}
