#pragma once

#include "type/Refusal.h"
#include "type/StringValue.h"

#include <array>
#include <compare>
#include <concepts>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <string>
#include <string_view>

/// \file
/// \brief AL `Guid` -- sixteen bytes that identify a record anywhere.

namespace agiru {

/// \brief AL `Guid`.
///
/// From `guid-data-type.md`: "Represents a 16 byte binary data type ... The GUID is a 16-byte
/// binary data type that can be logically grouped into the following subgroups: 4byte-2byte-2byte-
/// 2byte-6byte. The standard textual representation is {aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb}."
///
/// \note THE BRACES ARE PART OF THE TEXT AND NOT DECORATION. The page states the representation
///       with them, AL compares a Guid against a Text directly -- "You can assign and compare the
///       Text data type and the GUID data type" -- and BC code does compare against a braced
///       string. A `uuid` column renders without them, so the braces are added and removed at the
///       storage boundary rather than stored.
class Guid {
public:
  /// \brief The number of bytes in a Guid.
  static constexpr std::size_t kSize = 16;

  /// \brief The null GUID, all sixteen bytes zero, which AL calls an empty Guid.
  constexpr Guid() = default;

  /// \brief Holds sixteen given bytes.
  /// \param bytes The bytes, most significant first.
  constexpr explicit Guid(const std::array<std::uint8_t, kSize> &bytes) : bytes_(bytes) {}

  /// \brief AL `CreateGuid()`.
  ///
  /// \return A new random GUID.
  ///
  /// \note A version 4 UUID. `guid-data-type.md` says only that "the value is generated by an
  ///       algorithm, developed by Microsoft, which assures this uniqueness", and version 4 is what
  ///       every current platform generates; nothing in AL can tell the two apart, since the type
  ///       carries no version accessor.
  ///
  /// \note This is the one place in the runtime that is deliberately NOT deterministic, because the
  ///       AL method it implements is not either.
  [[nodiscard]] static Guid Create();

  /// \brief AL `CreateSequentialGuid()`.
  ///
  /// \return A new GUID whose leading bytes rise with time.
  ///
  /// \note `guid-createsequentialguid-method.md`: "Sequential GUIDs perform better when used as a
  ///       field in a key, because they are partially sequential instead of fully random." The
  ///       leading 48 bits are a millisecond timestamp and the rest is random -- the version 7
  ///       layout -- which is what gives a key inserted in creation order a rising prefix.
  [[nodiscard]] static Guid CreateSequentialGuid();

  /// \brief Reads the standard textual representation.
  ///
  /// \param text `{aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}`, with or without the braces.
  /// \return The GUID, or the null GUID when the text does not spell one.
  /// \return The GUID, or WHY the text is not one.
  ///
  /// \note IT REFUSES BY VALUE AND NOT BY UNWINDING, because AL asks this question with
  ///       `Evaluate`, which answers `false` -- the caller decides whether a text that is not a
  ///       GUID is an error (board:0621).
  [[nodiscard]] static std::expected<Guid, Refusal> FromText(std::string_view text);

  /// \brief AL assigns a Text to a Guid without a cast.
  ///
  /// \param text The GUID in its text form, with or without braces.
  /// \throws Error when the text is not a GUID.
  ///
  /// \note NOT `explicit`, BECAUSE AL IS NOT. `Notification.ID := DuplicateSymbolNotificationId`
  ///       assigns a `Label` holding `'8fcf129e-...'` to a Guid, and AL converts it on the spot.
  ///       A cast here would be a deviation the reader has to know about, for a conversion the
  ///       language performs silently.
  Guid(std::string_view text) : Guid(FromText(text).value_or(Guid{})) {}

  /// \brief A GUID from a string LITERAL -- `exit('bf856162-…')` from a procedure returning Guid.
  /// \param text The literal.
  /// \note A SECOND CONSTRUCTOR RATHER THAN A CAST AT THE CALL SITE: a literal reaches
  ///       `std::string_view` by one user-defined conversion and `Guid` by another, and C++ allows
  ///       only one of those in an implicit conversion sequence.
  Guid(const char *text) : Guid(std::string_view(text)) {}

  /// \brief AL passes a `Text[N]` where a `Guid` is declared, and converts it on the way.
  ///
  /// \tparam N The declared length, which the conversion ignores.
  /// \param text The GUID in its text form, with or without braces.
  /// \throws Error when the text is not a GUID.
  ///
  /// \note ARGUMENT PASSING IS ASSIGNMENT IN AL, and `guid-data-type.md` states the assignment.
  ///       `AltCustVATRegDocImpl` declares `AddAltCustVATRegNotificationId(): Text` and hands the
  ///       result straight to `MyNotifications.IsEnabled(NotificationId: Guid)`; nothing at the
  ///       call site says convert, because AL converts.
  ///
  /// \warning IT TAKES `Text` AND NOT `Code`, AND THAT IS A MEASURED LINE RATHER THAN A TASTE.
  ///          A converting constructor makes `Guid` a candidate wherever a text-shaped argument
  ///          meets an overload set, and AL resolves such a set by the DECLARED type while C++
  ///          ranks every user-defined conversion the same. `PriceSourceList.Add(Type, Code[20])`
  ///          beside `Add(Type, Guid)` then has no answer -- 7 call sites, measured 2026-09-07.
  ///          AL writes a GUID as `Text` and a code as `Code`, so the conversion follows that:
  ///          `Text` converts, `Code` does not, and a `Code` that really holds a GUID reaches one
  ///          through the assignment below.
  template <std::size_t N> Guid(const Text<N> &text) : Guid(text.Value()) {}

  /// \brief AL assigns a Text, a Code or a `std::string` to a Guid.
  ///
  /// \tparam T The text side -- a `Text[N]`, a `Code[N]`, a `std::string` or a literal.
  /// \param text The GUID in its text form, with or without braces.
  /// \return This Guid.
  /// \throws Error when the text is not a GUID.
  ///
  /// \note `guid-data-type.md` states this outright -- "You can assign and compare the Text data
  ///       type and the GUID data type", with `MyTableRec.MyGuid := MyTableRec.MyText` as its own
  ///       example. `ImportConsolidationFromAPI` writes `TempCompany.Id := JsonValue.AsText()`,
  ///       which is the same assignment one builtin further out.
  ///
  /// \note IT IS AN ASSIGNMENT AND NOT A CONSTRUCTOR, and that is the whole point. AL converts
  ///       text to a Guid where a Guid is ASSIGNED; it does not offer the conversion when it picks
  ///       an overload. A constructor would, and `PriceSourceList.Add(Type, Code[20])` beside
  ///       `Add(Type, Guid)` then has no answer -- 7 call sites, measured 2026-09-07. An
  ///       `operator=` converts exactly where AL converts.
  template <typename T>
    requires std::convertible_to<const T &, std::string_view>
  Guid &operator=(const T &text) {
    *this = FromText(std::string_view(text)).value_or(Guid{});
    return *this;
  }

  /// \return True when every byte is zero, which is AL's empty Guid.
  [[nodiscard]] constexpr bool IsNull() const {
    std::uint8_t any = 0;
    for (const std::uint8_t byte : bytes_) { any |= byte; }
    return any == 0;
  }

  /// \return The sixteen bytes.
  [[nodiscard]] constexpr const std::array<std::uint8_t, kSize> &Bytes() const { return bytes_; }

  /// \brief AL `Format(Guid)` -- the standard textual representation, braces and all.
  /// \return `{aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}` in lower case.
  [[nodiscard]] std::string ToText() const;

  /// \brief The same sixteen bytes without the braces, which is what a `uuid` column takes.
  /// \return `aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee`.
  [[nodiscard]] std::string ToStorageText() const;

  /// \brief Orders two GUIDs by their bytes.
  /// \param o The other GUID.
  /// \return The ordering.
  [[nodiscard]] constexpr std::strong_ordering operator<=>(const Guid &o) const = default;

  /// \brief Compares two GUIDs.
  /// \param o The other GUID.
  /// \return True when every byte matches.
  [[nodiscard]] constexpr bool operator==(const Guid &o) const = default;

private:
  std::array<std::uint8_t, kSize> bytes_{};
};

/// \brief AL compares a Text against a Guid, and compares them AS GUIDS.
///
/// \tparam T The text side -- a `Text[N]`, a `Code[N]`, a literal or a `std::string`.
/// \param left  The text.
/// \param right The Guid.
/// \return True when the text spells that GUID.
///
/// \note `guid-data-type.md`: "You can assign and compare the Text data type and the GUID data
///       type", and it lists BOTH spellings as supported -- braced and bare. So the comparison is
///       between two GUIDs and not between two strings, and
///       `'aaaaaaaa-…' = '{aaaaaaaa-…}'` is true where a text comparison would say false.
///       `AADApplicationCard` depends on exactly that: it strips the brackets and lower-cases
///       before comparing against a Guid.
///
/// \note IT IS SPELLED OUT RATHER THAN LEFT TO THE CONSTRUCTOR, because a Guid that can be built
///       from text makes `Text == Guid` ambiguous -- the text comparison and the Guid comparison
///       are then one conversion apiece.
///
/// \note THE GUID SIDE IS A CONSTRAINED TEMPLATE for the reason the `+` operators give: a plain
///       `const Guid &` lets every `Code == ''` in the tree reach this comparison by building a
///       Guid out of the literal, which is 2 000 ambiguous call sites (measured 2026-09-07).
template <typename T, typename G>
  requires std::convertible_to<const T &, std::string_view> && std::same_as<G, Guid>
[[nodiscard]] inline bool operator==(const T &left, const G &right) {
  return Guid::FromText(std::string_view(left)).value_or(Guid{}) == right;
}

/// \brief AL `+` on text and a Guid.
///
/// \param left  The text.
/// \param right The Guid.
/// \return The two joined, the Guid in its braced canonical form.
///
/// \note AL CONVERTS A GUID TO TEXT WHERE TEXT IS WANTED, which BC's own tests rely on --
///       `CopyStr(CreateGuid(), 1, 20)` compiles there. C++ has no such conversion and must not
///       gain one: a Guid is 16 bytes and its text is 38, so a conversion operator would need
///       storage on every Guid, and a Guid sits in every record as `SystemId`. The operator carries
///       it instead, where the text is actually wanted.
/// \note THE GUID SIDE TAKES NO CONVERSION, and that is why it is a constrained template rather
///       than a plain `const Guid &`. A Guid is assignable from AL text, so a plain parameter would
///       let `Text + std::string` reach this operator by converting the string to a Guid -- against
///       the text operator it belongs to and at the same rank, which is 50 ambiguous call sites
///       (measured 2026-09-07). `std::same_as` keeps the operator to the type it is written for.
template <typename G>
  requires std::same_as<G, Guid>
[[nodiscard]] inline std::string operator+(const ::agiru::Text<0> &left, const G &right) {
  return left + right.ToText();
}

/// \brief AL `+` on a Guid and text.
/// \param left  The Guid.
/// \param right The text.
/// \return The two joined.
/// \note Constrained for the reason above, from the other side.
template <typename G>
  requires std::same_as<G, Guid>
[[nodiscard]] inline std::string operator+(const G &left, std::string_view right) {
  return left.ToText() + std::string(right);
}

}
