#pragma once

#include <array>
#include <compare>
#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>

/// \file
/// \brief AL `Guid` -- sixteen bytes that identify a record anywhere.

namespace agiru {

/// \brief AL `Guid`.
///
/// From `guid-data-type.md`: "Represents a 16 byte binary data type ... The GUID is a 16-byte
/// binary data type that can be logically grouped into the following subgroups: 4byte-2byte-2byte-
/// 2byte-6byte. The standard textual representation is {aaaaaaaa-0000-1111-2222-bbbbbbbbbbbb}."
///
/// \note THE BRACES ARE PART OF THE TEXT AND NOT DECORATION. The page states the representation
///       with them, AL compares a Guid against a Text directly -- "You can assign and compare the
///       Text data type and the GUID data type" -- and BC code does compare against a braced
///       string. A `uuid` column renders without them, so the braces are added and removed at the
///       storage boundary rather than stored.
class Guid {
public:
  /// \brief The number of bytes in a Guid.
  static constexpr std::size_t kSize = 16;

  /// \brief The null GUID, all sixteen bytes zero, which AL calls an empty Guid.
  constexpr Guid() = default;

  /// \brief Holds sixteen given bytes.
  /// \param bytes The bytes, most significant first.
  constexpr explicit Guid(const std::array<std::uint8_t, kSize> &bytes) : bytes_(bytes) {}

  /// \brief AL `CreateGuid()`.
  ///
  /// \return A new random GUID.
  ///
  /// \note A version 4 UUID. `guid-data-type.md` says only that "the value is generated by an
  ///       algorithm, developed by Microsoft, which assures this uniqueness", and version 4 is what
  ///       every current platform generates; nothing in AL can tell the two apart, since the type
  ///       carries no version accessor.
  ///
  /// \note This is the one place in the runtime that is deliberately NOT deterministic, because the
  ///       AL method it implements is not either.
  [[nodiscard]] static Guid Create();

  /// \brief AL `CreateSequentialGuid()`.
  ///
  /// \return A new GUID whose leading bytes rise with time.
  ///
  /// \note `guid-createsequentialguid-method.md`: "Sequential GUIDs perform better when used as a
  ///       field in a key, because they are partially sequential instead of fully random." The
  ///       leading 48 bits are a millisecond timestamp and the rest is random -- the version 7
  ///       layout -- which is what gives a key inserted in creation order a rising prefix.
  [[nodiscard]] static Guid CreateSequential();

  /// \brief Reads the standard textual representation.
  ///
  /// \param text `{aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}`, with or without the braces.
  /// \return The GUID, or the null GUID when the text does not spell one.
  [[nodiscard]] static Guid FromText(std::string_view text);

  /// \return True when every byte is zero, which is AL's empty Guid.
  [[nodiscard]] constexpr bool IsNull() const {
    std::uint8_t any = 0;
    for (const std::uint8_t byte : bytes_) { any |= byte; }
    return any == 0;
  }

  /// \return The sixteen bytes.
  [[nodiscard]] constexpr const std::array<std::uint8_t, kSize> &Bytes() const { return bytes_; }

  /// \brief AL `Format(Guid)` -- the standard textual representation, braces and all.
  /// \return `{aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee}` in lower case.
  [[nodiscard]] std::string ToText() const;

  /// \brief The same sixteen bytes without the braces, which is what a `uuid` column takes.
  /// \return `aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee`.
  [[nodiscard]] std::string ToStorageText() const;

  /// \brief Orders two GUIDs by their bytes.
  /// \param o The other GUID.
  /// \return The ordering.
  [[nodiscard]] constexpr std::strong_ordering operator<=>(const Guid &o) const = default;

  /// \brief Compares two GUIDs.
  /// \param o The other GUID.
  /// \return True when every byte matches.
  [[nodiscard]] constexpr bool operator==(const Guid &o) const = default;

private:
  std::array<std::uint8_t, kSize> bytes_{};
};

} // namespace agiru
