if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CMAKE_CXX_LINK_LIBRARY_USING_agiru_registration
    "LINKER:--push-state,--no-as-needed" "<LINK_ITEM>" "LINKER:--pop-state")
  set(CMAKE_CXX_LINK_LIBRARY_USING_agiru_registration_SUPPORTED TRUE)
endif()

function(agiru_link_generated consumer library)
  get_target_property(kind "${library}" TYPE)
  if(kind STREQUAL "STATIC_LIBRARY")
    set(feature WHOLE_ARCHIVE)
  elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(feature agiru_registration)
  else()
    target_link_libraries("${consumer}" PRIVATE "${library}")
    return()
  endif()
  set_property(TARGET "${consumer}" PROPERTY "LINK_LIBRARY_OVERRIDE_${library}" "${feature}")
  target_link_libraries("${consumer}" PRIVATE "$<LINK_LIBRARY:${feature},${library}>")
endfunction()
