#include "type/Blob.h"
#include "type/File.h"
#include "type/Integer.h"
#include "type/Stream.h"
#include "type/StringValue.h"
#include "type/Text.h"

#include "Check.h"
#include "fixture/codeunit/StreamAliasConsumer.h"

#include <string_view>

int main() {
  return gate::Run("Generated Stream Aliases", [] {
    agiru::Fixture::StreamAliasConsumer_Codeunit consumer;
    constexpr agiru::Integer kWindowsEnglishUnitedStatesLcid = 1033;
    CHECK_TEXT("generated immutable culture factories retain their AL name",
               consumer.CultureName(kWindowsEnglishUnitedStatesLcid).Value(),
               "en-US");
    agiru::Blob note;
    CHECK_TEXT("generated immutable CLR factories preserve Unicode data",
               consumer.BinaryRoundTrip(note, "hällo").Value(),
               "hällo");
    CHECK_TRUE("generated binary write retains the CLR length prefix", note.Length() == 7);
    agiru::Blob blob;
    static_cast<void>(blob.CreateOutStream().WriteBytes("abcdef"));
    auto input = blob.CreateInStream();
    const auto alias = input;
    agiru::Text<0> text;
    CHECK_TRUE("generated by-value Read returns its count",
               consumer.ReadByValue(input, text, 2) == 2);
    CHECK_TEXT("generated by-value Read retains exact data", text.Value(), "ab");
    CHECK_TRUE("generated by-value Read advances the caller and aliases",
               input.Position() == 3 && alias.Position() == 3);
    CHECK_TRUE("generated assignment returns its count", consumer.CopyAndRead(input, text) == 1);
    CHECK_TEXT("generated assignment reads at the shared position", text.Value(), "c");
    CHECK_TRUE("generated assignment advances the caller", input.Position() == 4);
    CHECK_TRUE("generated by-value Reset succeeds", consumer.ResetByValue(input));
    CHECK_TRUE("generated by-value Reset affects every alias",
               input.Position() == 1 && alias.Position() == 1);
    agiru::Blob replacement;
    static_cast<void>(replacement.CreateOutStream().WriteBytes("xyz"));
    consumer.ConsumeAndRebind(input, text, replacement);
    CHECK_TEXT("generated local rebinding selects the new source", text.Value(), "x");
    CHECK_TRUE("generated local rebinding retains the caller's original target",
               input.Position() == 2 && alias.Position() == 2);
    consumer.Bind(input, replacement);
    CHECK_TEXT("generated var rebinding selects a fresh target", input.ReadBytes(1), "x");
    auto old = alias;
    CHECK_TEXT("generated var rebinding preserves existing aliases", old.ReadBytes(1), "b");
    auto escaped = consumer.InputFromLocalBlob();
    CHECK_TEXT("generated local BLOB input retains its provider", escaped.ReadBytes(100), "local");
    agiru::InStream linked;
    auto output = consumer.OutputFromLocalBlob(linked);
    CHECK_TRUE("generated local BLOB output retains its provider", output.WriteBytes("alive") > 0);
    CHECK_TEXT(
        "generated escaped streams share their retained provider", linked.ReadBytes(100), "alive");
    CHECK_TRUE("generated BLOB by-value writes mutate an independent value",
               consumer.WriteBlobByValue(blob) > static_cast<agiru::Integer>(blob.Length()));
    auto unchanged = blob.CreateInStream();
    CHECK_TEXT("generated BLOB by-value writes preserve the caller's bytes",
               unchanged.ReadBytes(100),
               "abcdef");
    agiru::File file;
    static_cast<void>(file.CreateTempFile());
    const auto name = file.Name();
    agiru::OutStream fileOutput;
    file.CreateOutStream(fileOutput);
    static_cast<void>(fileOutput.WriteBytes("first\r\nsecond"));
    file.Close();
    CHECK_TRUE("generated default File.Read does not split lines",
               consumer.ReadDefaultFile(name, text) == 13);
    CHECK_TEXT("generated binary file text retains line breaks", text.Value(), "first\r\nsecond");
    CHECK_TRUE("generated text-mode File.Read excludes line endings",
               consumer.ReadTextFile(name, text) == 5);
    CHECK_TEXT("generated text-mode file reads one line", text.Value(), "first");
    CHECK_TRUE("generated File.Pos begins at zero", consumer.FilePosition(name, 0) == 0);
    CHECK_TRUE("generated File.Pos matches its Seek offset", consumer.FilePosition(name, 2) == 2);
    static_cast<void>(file.Create(name));
    file.CreateOutStream(fileOutput);
    constexpr char terminated[] = "abc\0tail";
    static_cast<void>(fileOutput.WriteBytes(std::string_view(terminated, sizeof(terminated) - 1)));
    file.Close();
    CHECK_TRUE("generated binary File.Read preserves its declared capacity",
               consumer.ReadBoundedFile(name, text) == 4);
    CHECK_TEXT("generated binary file strips its terminator", text.Value(), "abc");
    static_cast<void>(agiru::File::Erase(name));
  });
}
